#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-3-Clause
#
# Copyright (c) 2026, Nevada System of Higher Education
# All rights reserved. See LICENSE for the full text.
"""
eduroam_maps.py -- build per-region eduroam service location maps.

Downloads the public eduroam-US location map, clips it against a set of region
boundary files, and writes one KML per region into the output directory together
with a leaderboard, a changelog and a machine-readable log of what changed.

Only regions whose service locations actually changed are rewritten, so the
published files can be committed straight to a GitHub Pages repository. It can
also push to that repository itself over the GitHub API, for hosts with no
checkout to commit from; see the publish section of the config.

Runs unattended with no arguments, from GitHub Actions or from cron. Nothing but
the Python 3.8+ standard library is required.

Regions are configuration: add a GeoJSON polygon named <code>.geojson to the
regions/ directory to add one, delete the file to remove one. No code changes
are needed to add, modify, or remove regions.

See README.md for setup and layout.
"""

from __future__ import annotations

import argparse
import base64
import datetime as dt
import fcntl
import hashlib
import json
import logging
import os
import posixpath
import re
import sys
import time
import urllib.error
import urllib.request
import xml.etree.ElementTree as ET
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

__version__ = "2.0"

LOG = logging.getLogger("eduroam")

HERE = os.path.dirname(os.path.abspath(__file__))

# Everything lives next to this script unless the environment says otherwise.
HOME = os.path.abspath(os.environ.get("EDUROAM_MAPS_HOME", HERE))


def _dir(env_name: str, default: str) -> str:
    """A directory under HOME, unless the environment says otherwise."""
    override = os.environ.get(env_name, "").strip()
    return os.path.abspath(override) if override else os.path.join(HOME, default)


# Overridable individually so a checkout can write straight into the directory
# Pages serves from, e.g. EDUROAM_OUTPUT_DIR=docs.
REGIONS_DIR = _dir("EDUROAM_REGIONS_DIR", "regions")
OUTPUT_DIR = _dir("EDUROAM_OUTPUT_DIR", "output")
STATE_DIR = _dir("EDUROAM_STATE_DIR", "state")
CONFIG_PATH = os.environ.get("EDUROAM_CONFIG", "").strip() or os.path.join(HOME, "config.json")

DEFAULT_CONFIG = {
    # Upstream eduroam location database (G\u00c9ANT).
    "source_url": "https://monitor.eduroam.org/kml/us.kml",
    # Don't even ask upstream if the cached copy is younger than this.  Lets the
    # job be run several times a day without hammering the source.
    "min_refresh_seconds": 3600,
    "http_timeout": 60,
    # "locations": rebuild a region only when service locations are added,
    #              removed or moved (recommended -- ignores upstream metadata
    #              churn such as changing AP counts).
    # "any":       rebuild whenever anything at all about a placemark changes.
    "regenerate_on": "locations",
    # Optional marker icon for the generated placemarks. Empty means no style at
    # all, so the maps reference no third-party assets; set it to a URL you are
    # happy to depend on if you want custom pins.
    "placemark_icon_url": "",
    # Attribution shown at the foot of the leaderboard page, in LEADERBOARD.md
    # and inside each KML file. Footnotes accept plain text plus [label](url)
    # links; nothing else is interpreted, and non-http(s) URLs are dropped.
    # "publisher_note" is rendered first and is the place to record who
    # operates the site and under whose authority.
    "attribution": {
        "publisher_note": "",
        "footnotes": [
            "Service location data comes from the eduroam location database "
            "published by G\u00c9ANT ([monitor.eduroam.org](https://monitor.eduroam.org/kml/us.kml)). "
            "These maps are derived from it and are not an official G\u00c9ANT or "
            "eduroam publication.",
            "eduroam is a registered trademark of G\u00c9ANT Vereniging.",
            "Region boundaries are derived from US Census Bureau cartographic "
            "boundary files, which as works of the US federal government are in "
            "the public domain.",
            "Maps generated by eduroam-maps, which is BSD 3-Clause licensed.",
        ],
    },
    # Refuse to run if the fresh download has fewer placemarks than this, or if
    # it would delete more than this fraction of the known locations.  Protects
    # the published maps from a bad upstream day.  EDUROAM_FORCE=1 overrides.
    "min_placemarks": 100,
    "max_delete_ratio": 0.5,
    # Keep the published changelog and machine-readable log from growing
    # without bound. Roughly one entry per day of real change.
    "changelog_max_entries": 365,
    "changes_max_entries": 365,
    # Showing the last-checked date rewrites the leaderboard every day even when
    # nothing changed.  Off by default so revisions track real changes.
    "leaderboard_show_last_checked": False,
    "publish": {
        "enabled": True,
        # The GitHub Pages repository the maps are published to, "owner/repo".
        "repo": "",
        # Branch Pages serves from. GitHub Pages can only serve from the repo
        # root or a /docs directory, so "path" must be "" or "docs".
        "branch": "gh-pages",
        "path": "",
        "commit_message": "Update eduroam service location maps",
        "author_name": "github-actions[bot]",
        "author_email": "41898282+github-actions[bot]@users.noreply.github.com",
        # Leave empty to derive https://<owner>.github.io/<repo>/ or to read the
        # real URL back from the Pages API.
        "site_url": "",
        # Turn Pages on automatically the first time (needs a token with repo
        # admin rights; harmless if it is already on).
        "enable_pages": True,
        "token_env": "GITHUB_TOKEN",
        "token_file": "",
    },
}

LEADERBOARD_NAME = "LEADERBOARD.md"
CHANGELOG_NAME = "CHANGELOG.md"
CHANGES_JSONL = "changes.jsonl"
INDEX_NAME = "index.html"
NOJEKYLL_NAME = ".nojekyll"

GITHUB_API = os.environ.get("GITHUB_API_URL", "https://api.github.com").rstrip("/")
USER_AGENT = f"eduroam-maps/{__version__}"


# --------------------------------------------------------------------------
# small helpers
# --------------------------------------------------------------------------

def utcnow() -> dt.datetime:
    return dt.datetime.now(dt.timezone.utc)


def iso(ts: dt.datetime) -> str:
    return ts.strftime("%Y-%m-%dT%H:%M:%SZ")


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def squash(text: Optional[str]) -> str:
    """Collapse all whitespace runs to single spaces and strip."""
    return re.sub(r"\s+", " ", text or "").strip()


def coord(value: float) -> str:
    """Format a coordinate deterministically so output never jitters."""
    text = f"{value:.7f}".rstrip("0").rstrip(".")
    return "0" if text in ("", "-0") else text


def xml_text(text: str) -> str:
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


def cdata(text: str) -> str:
    """Wrap text in CDATA, splitting any literal ']]>' so it stays valid."""
    return "<![CDATA[" + text.replace("]]>", "]]]]><![CDATA[>") + "]]>"


def read_json(path: str, default):
    try:
        with open(path, encoding="utf-8") as fh:
            return json.load(fh)
    except (OSError, ValueError):
        return default


def write_atomic(path: str, data: bytes) -> None:
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    tmp = f"{path}.tmp.{os.getpid()}"
    with open(tmp, "wb") as fh:
        fh.write(data)
        fh.flush()
        os.fsync(fh.fileno())
    os.replace(tmp, path)


def write_text_if_changed(path: str, text: str) -> bool:
    """Write text only when it differs.  Returns True if the file changed."""
    data = text.encode("utf-8")
    try:
        with open(path, "rb") as fh:
            if fh.read() == data:
                return False
    except OSError:
        pass
    write_atomic(path, data)
    return True


def deep_merge(base: dict, override: dict) -> dict:
    out = dict(base)
    for key, value in (override or {}).items():
        if isinstance(value, dict) and isinstance(out.get(key), dict):
            out[key] = deep_merge(out[key], value)
        else:
            out[key] = value
    return out


def truthy_env(name: str) -> bool:
    return os.environ.get(name, "").strip().lower() in ("1", "true", "yes", "on")


# --------------------------------------------------------------------------
# geometry -- point in polygon, no third-party libraries
# --------------------------------------------------------------------------

class Ring:
    """A single closed linear ring with a cached bounding box."""

    __slots__ = ("points", "minx", "miny", "maxx", "maxy")

    def __init__(self, raw: Sequence[Sequence[float]]):
        pts = [(float(p[0]), float(p[1])) for p in raw]
        if pts and pts[0] != pts[-1]:
            pts.append(pts[0])
        self.points = pts
        xs = [p[0] for p in pts]
        ys = [p[1] for p in pts]
        self.minx, self.maxx = (min(xs), max(xs)) if xs else (0.0, 0.0)
        self.miny, self.maxy = (min(ys), max(ys)) if ys else (0.0, 0.0)

    def contains(self, x: float, y: float) -> bool:
        if x < self.minx or x > self.maxx or y < self.miny or y > self.maxy:
            return False
        pts = self.points
        inside = False
        x1, y1 = pts[0]
        for x2, y2 in pts[1:]:
            if (y1 > y) != (y2 > y):
                if x < (x2 - x1) * (y - y1) / (y2 - y1) + x1:
                    inside = not inside
            x1, y1 = x2, y2
        return inside


class Boundary:
    """One or more polygons (with holes) loaded from a GeoJSON file."""

    def __init__(self, parts: List[Tuple[Ring, List[Ring]]]):
        self.parts = parts
        if parts:
            self.minx = min(p[0].minx for p in parts)
            self.miny = min(p[0].miny for p in parts)
            self.maxx = max(p[0].maxx for p in parts)
            self.maxy = max(p[0].maxy for p in parts)
        else:
            self.minx = self.miny = self.maxx = self.maxy = 0.0

    def __bool__(self) -> bool:
        return bool(self.parts)

    def contains(self, x: float, y: float) -> bool:
        if not self.parts:
            return False
        if x < self.minx or x > self.maxx or y < self.miny or y > self.maxy:
            return False
        for exterior, holes in self.parts:
            if exterior.contains(x, y) and not any(h.contains(x, y) for h in holes):
                return True
        return False

    @staticmethod
    def _polygons(geom: dict) -> Iterable[Sequence]:
        kind = (geom or {}).get("type")
        coords = (geom or {}).get("coordinates") or []
        if kind == "Polygon":
            yield coords
        elif kind == "MultiPolygon":
            for poly in coords:
                yield poly
        elif kind == "GeometryCollection":
            for sub in (geom.get("geometries") or []):
                yield from Boundary._polygons(sub)

    @classmethod
    def from_geojson(cls, data: dict) -> "Boundary":
        kind = data.get("type")
        if kind == "FeatureCollection":
            geoms = [(f or {}).get("geometry") for f in data.get("features") or []]
        elif kind == "Feature":
            geoms = [data.get("geometry")]
        else:
            geoms = [data]
        parts: List[Tuple[Ring, List[Ring]]] = []
        for geom in geoms:
            for poly in cls._polygons(geom):
                if poly:
                    parts.append((Ring(poly[0]), [Ring(r) for r in poly[1:]]))
        return cls(parts)


# --------------------------------------------------------------------------
# regions
# --------------------------------------------------------------------------

class Region:
    def __init__(self, code: str, name: str, path: str, boundary: Boundary, digest: str):
        self.code = code
        self.name = name
        self.path = path
        self.boundary = boundary
        self.digest = digest

    @property
    def filename(self) -> str:
        return f"eduroam_{self.code}.kml"


# A region file is "<code>.geojson" (or ".json"); the stem is the region code.
REGION_FILE_RE = re.compile(r"^(?P<code>[A-Za-z0-9][A-Za-z0-9_-]*)\.(?:geo)?json$")

NAME_KEYS = ("NAME", "name", "Name", "STATE_NAME", "NAME_1", "region", "REGION")


def region_display_name(data: dict, code: str) -> str:
    """Pick a human readable name out of the GeoJSON, else fall back to the code."""
    for key in NAME_KEYS:
        value = data.get(key)
        if isinstance(value, str) and value.strip():
            return value.strip()
    features = data.get("features") or ([data] if data.get("type") == "Feature" else [])
    for feature in features:
        props = (feature or {}).get("properties") or {}
        for key in NAME_KEYS:
            value = props.get(key)
            if isinstance(value, str) and value.strip():
                return value.strip()
    return code.upper()


def load_regions(regions_dir: str) -> List[Region]:
    if not os.path.isdir(regions_dir):
        raise SystemExit(f"No regions directory at {regions_dir!r} -- nothing to do.")

    regions: Dict[str, Region] = {}
    for entry in sorted(os.listdir(regions_dir)):
        path = os.path.join(regions_dir, entry)
        if not os.path.isfile(path) or entry.startswith("."):
            continue
        match = REGION_FILE_RE.match(entry)
        if not match:
            LOG.debug("Ignoring %s (not a region file)", entry)
            continue
        code = match.group("code").lower()

        try:
            with open(path, "rb") as fh:
                raw = fh.read()
            data = json.loads(raw.decode("utf-8"))
        except (OSError, ValueError) as exc:
            LOG.warning("Skipping region %r: cannot read %s (%s)", code, entry, exc)
            continue

        boundary = Boundary.from_geojson(data)
        if not boundary:
            LOG.warning("Skipping region %r: %s has no polygon geometry", code, entry)
            continue
        if code in regions:
            LOG.warning("Skipping duplicate region file %s (%r already loaded)", entry, code)
            continue

        regions[code] = Region(
            code=code,
            name=region_display_name(data, code),
            path=path,
            boundary=boundary,
            digest=sha256_bytes(raw),
        )

    if not regions:
        raise SystemExit(f"No usable region files found in {regions_dir!r}.")
    return [regions[code] for code in sorted(regions)]


# --------------------------------------------------------------------------
# the upstream map
# --------------------------------------------------------------------------

class Placemark:
    __slots__ = ("org", "loc", "lon", "lat", "description")

    def __init__(self, org: str, loc: str, lon: float, lat: float, description: str):
        self.org = org
        self.loc = loc
        self.lon = lon
        self.lat = lat
        self.description = description

    @property
    def key(self) -> Tuple[str, str, str, str]:
        """Identity of a service location: who, where by name, where on earth."""
        return (self.org, self.loc, coord(self.lon), coord(self.lat))

    @property
    def sort_key(self) -> Tuple:
        return (self.org.casefold(), self.loc.casefold(), self.lon, self.lat, self.description)

    def record(self) -> dict:
        """Full detail, for the changelog and the machine-readable log."""
        return {
            "org": self.org,
            "loc": self.loc,
            "lon": coord(self.lon),
            "lat": coord(self.lat),
            "description": self.description,
        }

    def inventory_record(self) -> dict:
        """
        Same identity, but the description reduced to a short digest.

        The description is only ever compared, never read back out, and the
        inventory is committed, so there is no reason to carry the full text.
        """
        return {
            "org": self.org,
            "loc": self.loc,
            "lon": coord(self.lon),
            "lat": coord(self.lat),
            "dhash": sha256_bytes(self.description.encode("utf-8"))[:16],
        }


LOC_NAME_RE = re.compile(r"<b>\s*Name:\s*</b>\s*(.*?)\s*(?:<br\s*/?>|$)", re.I | re.S)


def local_name(tag: str) -> str:
    return tag.rpartition("}")[2]


def find_child(element, name: str):
    for child in element:
        if local_name(child.tag) == name:
            return child
    return None


def child_text(element, name: str) -> str:
    child = find_child(element, name)
    return squash(child.text if child is not None else "")


def parse_source_kml(data: bytes) -> List[Placemark]:
    """Parse the upstream KML into a deduplicated, alphabetically sorted list."""
    try:
        root = ET.fromstring(data)
    except ET.ParseError as exc:
        raise SystemExit(f"Upstream map is not valid XML: {exc}")

    found: Dict[Tuple[str, str, str, str], Placemark] = {}
    duplicates = 0
    skipped = 0

    for element in root.iter():
        if local_name(element.tag) != "Placemark":
            continue
        point = find_child(element, "Point")
        if point is None:
            skipped += 1
            continue
        raw_coords = child_text(point, "coordinates")
        bits = [b for b in raw_coords.replace(" ", ",").split(",") if b]
        if len(bits) < 2:
            skipped += 1
            continue
        try:
            lon, lat = float(bits[0]), float(bits[1])
        except ValueError:
            skipped += 1
            continue
        if not (-180.0 <= lon <= 180.0 and -90.0 <= lat <= 90.0):
            skipped += 1
            continue

        org = squash(child_text(element, "name"))
        description = squash(child_text(element, "description"))
        match = LOC_NAME_RE.search(description)
        loc = squash(match.group(1)) if match else ""

        placemark = Placemark(org, loc, lon, lat, description)
        if placemark.key in found:
            duplicates += 1
            continue
        found[placemark.key] = placemark

    if duplicates:
        LOG.info("Dropped %d duplicate placemark(s) from the upstream map", duplicates)
    if skipped:
        LOG.info("Skipped %d placemark(s) with no usable point", skipped)

    return sorted(found.values(), key=lambda p: p.sort_key)


def fetch_source(cfg: dict, force: bool) -> Tuple[bytes, dict]:
    """
    Return (kml bytes, metadata).

    Uses a cached copy plus a conditional GET so that running several times a day
    costs at most one small 304 response -- and, inside min_refresh_seconds,
    no request at all.
    """
    cache_path = os.path.join(STATE_DIR, "source.kml")
    meta_path = os.path.join(STATE_DIR, "source.meta.json")
    meta = read_json(meta_path, {}) or {}
    url = cfg["source_url"]

    cached: Optional[bytes] = None
    if os.path.exists(cache_path) and meta.get("url") == url:
        try:
            with open(cache_path, "rb") as fh:
                cached = fh.read()
        except OSError:
            cached = None

    if cached and not force:
        age = time.time() - float(meta.get("fetched_at_epoch") or 0)
        if 0 <= age < float(cfg["min_refresh_seconds"]):
            LOG.info(
                "Using cached upstream map (%.0f min old, under the %.0f min refresh window)",
                age / 60.0,
                float(cfg["min_refresh_seconds"]) / 60.0,
            )
            return cached, meta

    request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    if cached and not force:
        if meta.get("etag"):
            request.add_header("If-None-Match", meta["etag"])
        if meta.get("last_modified"):
            request.add_header("If-Modified-Since", meta["last_modified"])

    LOG.info("Checking %s for a newer map", url)
    try:
        with urllib.request.urlopen(request, timeout=cfg["http_timeout"]) as response:
            body = response.read()
            headers = response.headers
    except urllib.error.HTTPError as exc:
        if exc.code == 304 and cached:
            LOG.info("Upstream map unchanged (HTTP 304)")
            meta["fetched_at_epoch"] = time.time()
            meta["fetched_at"] = iso(utcnow())
            write_atomic(meta_path, json.dumps(meta, indent=2, sort_keys=True).encode())
            return cached, meta
        raise SystemExit(f"Failed to fetch {url}: HTTP {exc.code} {exc.reason}")
    except (urllib.error.URLError, OSError) as exc:
        raise SystemExit(f"Failed to fetch {url}: {exc}")

    if not body.strip():
        raise SystemExit("Upstream map came back empty -- refusing to touch the published maps.")

    digest = sha256_bytes(body)
    unchanged = digest == meta.get("sha256")
    meta = {
        "url": url,
        "sha256": digest,
        "bytes": len(body),
        "etag": headers.get("ETag") or "",
        "last_modified": headers.get("Last-Modified") or "",
        "fetched_at": iso(utcnow()),
        "fetched_at_epoch": time.time(),
    }
    write_atomic(cache_path, body)
    write_atomic(meta_path, json.dumps(meta, indent=2, sort_keys=True).encode())
    LOG.info(
        "Downloaded %.1f KiB (%s)",
        len(body) / 1024.0,
        "identical to the cached copy" if unchanged else "content changed",
    )
    return body, meta


# --------------------------------------------------------------------------
# KML output
# --------------------------------------------------------------------------

STYLE_ID = "eduroam"


def build_kml(
    region: Region,
    placemarks: Sequence[Placemark],
    icon_href: str = "",
    attribution: str = "",
) -> str:
    """
    Render a region's KML.

    Deliberately contains no timestamps or other volatile content: identical
    input always produces a byte-identical file, which is what lets the job
    publish only the regions that really changed.

    With no icon_href the placemarks carry no style and the viewer draws its own
    default marker, so the output depends on nothing but this program.
    """
    icon_href = (icon_href or "").strip()
    # Sorted here rather than relying on the caller, so the guarantee holds for
    # any input: alphabetical output is what keeps the published files diffable.
    placemarks = sorted(placemarks, key=lambda p: p.sort_key)
    out: List[str] = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<kml xmlns="http://www.opengis.net/kml/2.2">',
        "  <Document>",
        f"    <name>eduroam \u2014 {xml_text(region.name)}</name>",
        "    <description>"
        + cdata(
            f"{len(placemarks)} eduroam service location"
            f"{'' if len(placemarks) == 1 else 's'} in {region.name}."
            + (f"<br><br>{attribution}" if attribution else "")
        )
        + "</description>",
        "    <open>1</open>",
    ]
    if icon_href:
        out.extend(
            [
                f'    <Style id="{STYLE_ID}">',
                "      <IconStyle>",
                f"        <Icon><href>{xml_text(icon_href)}</href></Icon>",
                "      </IconStyle>",
                "    </Style>",
            ]
        )
    for placemark in placemarks:
        out.extend(
            [
                "    <Placemark>",
                f"      <name>{xml_text(placemark.org)}</name>",
            ]
        )
        if icon_href:
            out.append(f"      <styleUrl>#{STYLE_ID}</styleUrl>")
        out.extend(
            [
                f"      <description>{cdata(placemark.description)}</description>",
                "      <Point>",
                f"        <coordinates>{coord(placemark.lon)},{coord(placemark.lat)},0</coordinates>",
                "      </Point>",
                "    </Placemark>",
            ]
        )
    out.extend(["  </Document>", "</kml>", ""])
    return "\n".join(out)


# --------------------------------------------------------------------------
# diffing
# --------------------------------------------------------------------------

class RegionDiff:
    def __init__(self, region: Region, previous: dict, current: Sequence[Placemark]):
        self.region = region
        self.count = len(current)
        self.previous_count = int(previous.get("count", 0)) if previous else 0
        self.first_run = not previous

        old_records = {
            (r["org"], r["loc"], r["lon"], r["lat"]): r
            for r in (previous or {}).get("placemarks", [])
        }
        live = {p.key: p for p in current}
        new_records = {key: p.inventory_record() for key, p in live.items()}

        added_keys = sorted(set(new_records) - set(old_records))
        removed_keys = sorted(set(old_records) - set(new_records))

        # A location that kept its name but changed coordinates reads much
        # better as "moved" than as an unrelated add plus delete.
        added_by_name: Dict[Tuple[str, str], List[tuple]] = {}
        for key in added_keys:
            added_by_name.setdefault((key[0], key[1]), []).append(key)
        removed_by_name: Dict[Tuple[str, str], List[tuple]] = {}
        for key in removed_keys:
            removed_by_name.setdefault((key[0], key[1]), []).append(key)

        self.moved: List[dict] = []
        paired_added, paired_removed = set(), set()
        for name, olds in removed_by_name.items():
            news = added_by_name.get(name) or []
            if len(olds) == 1 and len(news) == 1:
                old_key, new_key = olds[0], news[0]
                paired_removed.add(old_key)
                paired_added.add(new_key)
                self.moved.append(
                    {
                        "org": name[0],
                        "loc": name[1],
                        "from": {"lon": old_key[2], "lat": old_key[3]},
                        "to": {"lon": new_key[2], "lat": new_key[3]},
                    }
                )
        self.moved.sort(key=lambda m: (m["org"].casefold(), m["loc"].casefold()))

        self.added = [live[k].record() for k in added_keys if k not in paired_added]
        self.removed = [
            {k2: v for k2, v in old_records[k].items() if k2 != "dhash"}
            for k in removed_keys
            if k not in paired_removed
        ]

        # Metadata-only edits (an AP count ticking over, say) are tracked but do
        # not, by default, count as a change worth republishing for.
        self.metadata_changed = sum(
            1
            for key, record in new_records.items()
            if key in old_records and old_records[key].get("dhash") != record["dhash"]
        )

    @property
    def locations_changed(self) -> bool:
        return bool(self.added or self.removed or self.moved)

    @property
    def anything_changed(self) -> bool:
        return self.locations_changed or bool(self.metadata_changed)

    def summary(self) -> dict:
        record = {
            "name": self.region.name,
            "count": self.count,
            "previous_count": self.previous_count,
            "metadata_changed": self.metadata_changed,
        }
        if self.first_run:
            # Don't dump every location on the very first run for a region;
            # record it as a baseline instead.
            record["baseline"] = True
            return record
        record.update({"added": self.added, "removed": self.removed, "moved": self.moved})
        return record


# --------------------------------------------------------------------------
# reports
# --------------------------------------------------------------------------

MD_LINK_RE = re.compile(r"\[([^\]]+)\]\((https?://[^)\s\"']+)\)")


def attr(value: str) -> str:
    """Escape a string for use inside a double-quoted HTML/XML attribute."""
    return xml_text(value).replace('"', "&quot;")


def markdown_links_to_html(text: str) -> str:
    """
    Render the tiny subset of Markdown allowed in attribution footnotes.

    Only [label](http(s)://...) becomes a link; everything else is escaped, so a
    footnote can never inject markup into the page.
    """
    out: List[str] = []
    pos = 0
    for match in MD_LINK_RE.finditer(text):
        out.append(xml_text(text[pos:match.start()]))
        out.append(f'<a href="{attr(match.group(2))}">{xml_text(match.group(1))}</a>')
        pos = match.end()
    out.append(xml_text(text[pos:]))
    return "".join(out)


def attribution_lines(cfg: dict) -> List[str]:
    """Publisher note first, then the standing footnotes, all as Markdown."""
    block = cfg.get("attribution") or {}
    lines = []
    publisher = str(block.get("publisher_note") or "").strip()
    if publisher:
        lines.append(publisher)
    for note in block.get("footnotes") or []:
        note = str(note or "").strip()
        if note:
            lines.append(note)
    return lines


def attribution_for_kml(cfg: dict) -> str:
    """The same attribution, as an HTML fragment for a KML <description>."""
    lines = attribution_lines(cfg)
    if not lines:
        return ""
    return "<br>".join(markdown_links_to_html(line) for line in lines)


def attribution_digest(cfg: dict) -> str:
    """Changing the attribution has to rebuild the maps that carry it."""
    return sha256_bytes(attribution_for_kml(cfg).encode("utf-8"))


def site_file_url(site_url: str, filename: str) -> str:
    if not site_url:
        return ""
    return site_url.rstrip("/") + "/" + filename


def ranked_rows(
    rows: List[Tuple[Region, int, Optional[int]]]
) -> List[Tuple[int, Region, int, str]]:
    """
    Sort regions by count then name, assigning equal ranks to ties.

    Shared by the Markdown and HTML leaderboards so the two can never drift.
    """
    ordered = sorted(rows, key=lambda r: (-r[1], r[0].name.casefold()))
    out = []
    rank = 0
    previous_count = None
    for index, (region, count, before) in enumerate(ordered, start=1):
        if count != previous_count:
            rank, previous_count = index, count
        out.append((rank, region, count, _delta(count, before)))
    return out


def _delta(count: int, before: Optional[int]) -> str:
    if before is None:
        return "new"
    if count > before:
        return f"+{count - before}"
    if count < before:
        return f"\u2212{before - count}"
    return "\u2013"


def render_leaderboard(
    rows: List[Tuple[Region, int, Optional[int]]],
    cfg: dict,
    last_changed: str,
    checked: str,
    site_url: str,
    total: int,
) -> str:
    ranked = ranked_rows(rows)

    lines = [
        "# eduroam service locations by region",
        "",
        f"**{total:,}** eduroam service locations across **{len(ranked)}** regions.",
        "",
        f"Data last changed: {last_changed}" if last_changed else "Data last changed: (first run)",
    ]
    if cfg.get("leaderboard_show_last_checked"):
        lines.extend(["", f"Last checked: {checked}"])
    lines.extend(
        [
            "",
            "Source: the public eduroam location database at "
            "[monitor.eduroam.org](https://monitor.eduroam.org/kml/us.kml).",
            "",
            "| # | Region | Locations | Change | Map |",
            "|--:|:-------|----------:|-------:|:----|",
        ]
    )

    for rank, region, count, delta in ranked:
        url = site_file_url(site_url, region.filename)
        link = f"[KML]({url})" if url else f"`{region.filename}`"
        lines.append(f"| {rank} | {region.name} | {count:,} | {delta} | {link} |")

    lines.extend(
        [
            "",
            "_Totals count only locations that fall inside a configured region boundary, "
            "and each location once even where regions overlap._",
        ]
    )

    notes = attribution_lines(cfg)
    if notes:
        lines.extend(["", "---", ""])
        lines.extend(f"{i}. {note}" for i, note in enumerate(notes, start=1))
    lines.append("")
    return "\n".join(lines)


INDEX_CSS = """
:root { color-scheme: light dark; }
* { box-sizing: border-box; }
body { margin: 0; padding: 2.5rem 1.25rem 4rem;
       font: 16px/1.55 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
       color: #1b1f24; background: #fff; }
main { max-width: 56rem; margin: 0 auto; }
h1 { font-size: 1.75rem; margin: 0 0 .35rem; letter-spacing: -.01em; }
p.lede { margin: 0 0 .25rem; font-size: 1.05rem; }
p.meta { margin: .1rem 0; color: #57606a; font-size: .9rem; }
table { width: 100%; border-collapse: collapse; margin-top: 1.75rem; font-variant-numeric: tabular-nums; }
th, td { padding: .5rem .6rem; border-bottom: 1px solid #d8dee4; text-align: left; }
th { font-size: .78rem; text-transform: uppercase; letter-spacing: .06em; color: #57606a; font-weight: 600; }
td.num, th.num { text-align: right; }
tbody tr:hover { background: #f6f8fa; }
.up { color: #1a7f37; } .down { color: #cf222e; }
.same { color: #8c959f; } .fresh { color: #8250df; }
a { color: #0969da; text-decoration: none; }
a:hover { text-decoration: underline; }
footer { margin-top: 2.5rem; color: #57606a; font-size: .85rem; }
footer hr { border: 0; border-top: 1px solid #d8dee4; margin: 1.5rem 0 1rem; }
ol.notes { padding-left: 1.2rem; margin: 0; }
ol.notes li { margin: .35rem 0; }
code { background: #f6f8fa; padding: .1rem .3rem; border-radius: 4px; font-size: .85em; }
@media (prefers-color-scheme: dark) {
  body { background: #0d1117; color: #e6edf3; }
  th, td, footer hr { border-bottom-color: #30363d; border-top-color: #30363d; }
  th, p.meta, footer { color: #9198a1; }
  tbody tr:hover { background: #161b22; }
  a { color: #4493f8; }
  code { background: #161b22; }
}
"""


def render_index_html(
    rows: List[Tuple[Region, int, Optional[int]]],
    cfg: dict,
    last_changed: str,
    site_url: str,
    total: int,
) -> str:
    """A small static landing page for the Pages site. Deterministic: no clocks."""
    ranked = ranked_rows(rows)

    body = [
        "<!DOCTYPE html>",
        '<html lang="en">',
        "<head>",
        '<meta charset="utf-8">',
        '<meta name="viewport" content="width=device-width, initial-scale=1">',
        "<title>eduroam service locations by region</title>",
        f"<style>{INDEX_CSS}</style>",
        "</head>",
        "<body>",
        "<main>",
        "<h1>eduroam service locations by region</h1>",
        f'<p class="lede">{total:,} service locations across {len(ranked)} regions.</p>',
        f'<p class="meta">Data last changed: {xml_text(last_changed or "first run")}</p>',
        '<p class="meta">Source: the public eduroam location database at '
        '<a href="https://monitor.eduroam.org/kml/us.kml">monitor.eduroam.org</a>. '
        'Each region is a KML file you can point Google Maps at.</p>',
        "<table>",
        '<thead><tr><th class="num">#</th><th>Region</th>'
        '<th class="num">Locations</th><th class="num">Change</th><th>Map</th></tr></thead>',
        "<tbody>",
    ]

    for rank, region, count, delta in ranked:
        css = "same"
        if delta.startswith("+"):
            css = "up"
        elif delta.startswith("\u2212"):
            css = "down"
        elif delta == "new":
            css = "fresh"
        url = site_file_url(site_url, region.filename) or region.filename
        body.append(
            f"<tr><td class=\"num\">{rank}</td><td>{xml_text(region.name)}</td>"
            f"<td class=\"num\">{count:,}</td>"
            f"<td class=\"num {css}\">{delta}</td>"
            f'<td><a href="{xml_text(url)}">{xml_text(region.filename)}</a></td></tr>'
        )

    body.extend(
        [
            "</tbody>",
            "</table>",
            "<footer>",
            '<p>Full history of additions, removals and moves: '
            f'<a href="{xml_text(site_file_url(site_url, CHANGELOG_NAME) or CHANGELOG_NAME)}">'
            "CHANGELOG.md</a> "
            f'(machine readable: <a href="{xml_text(site_file_url(site_url, CHANGES_JSONL) or CHANGES_JSONL)}">'
            "changes.jsonl</a>).</p>",
            "<p>Totals count only locations inside a configured region boundary, "
            "and each location once even where regions overlap.</p>",
        ]
    )
    notes = attribution_lines(cfg)
    if notes:
        body.append('<hr><ol class="notes">')
        body.extend(f"<li>{markdown_links_to_html(note)}</li>" for note in notes)
        body.append("</ol>")
    body.extend(
        [
            "</footer>",
            "</main>",
            "</body>",
            "</html>",
            "",
        ]
    )
    return "\n".join(body)


def _label(record: dict) -> str:
    return f"{record['org']} \u2014 {record['loc']}" if record.get("loc") else record["org"]


def render_change_entry(stamp: str, diffs: List[RegionDiff]) -> str:
    """
    Render one dated changelog entry.

    Regions seen for the first time are recorded as a one-line baseline rather
    than thousands of "added" lines, so the very first run doesn't produce a
    changelog nobody can read.
    """
    baselines = sorted(
        (d for d in diffs if d.first_run and d.count),
        key=lambda d: d.region.name.casefold(),
    )
    changed = sorted(
        (d for d in diffs if d.locations_changed and not d.first_run),
        key=lambda d: d.region.name.casefold(),
    )
    if not baselines and not changed:
        return ""

    added = sum(len(d.added) for d in changed)
    removed = sum(len(d.removed) for d in changed)
    moved = sum(len(d.moved) for d in changed)

    bits = []
    if added:
        bits.append(f"{added} added")
    if removed:
        bits.append(f"{removed} removed")
    if moved:
        bits.append(f"{moved} moved")

    lines = [f"## {stamp}", ""]
    if bits:
        lines.extend([f"{', '.join(bits)} across {len(changed)} region(s).", ""])

    for diff in changed:
        lines.extend([f"### {diff.region.name} \u2014 {diff.previous_count} \u2192 {diff.count}", ""])
        for record in diff.added:
            lines.append(f"- **added** {_label(record)} `({record['lat']}, {record['lon']})`")
        for record in diff.removed:
            lines.append(f"- **removed** {_label(record)} `({record['lat']}, {record['lon']})`")
        for record in diff.moved:
            lines.append(
                f"- **moved** {_label(record)} "
                f"`({record['from']['lat']}, {record['from']['lon']})` \u2192 "
                f"`({record['to']['lat']}, {record['to']['lon']})`"
            )
        lines.append("")

    if baselines:
        total = sum(d.count for d in baselines)
        lines.extend(
            [
                f"### Baseline recorded for {len(baselines)} region(s), {total:,} location(s)",
                "",
                "Locations present when the region was first tracked; individual "
                "additions are listed from the next run onwards.",
                "",
            ]
        )
        for diff in baselines:
            lines.append(f"- {diff.region.name}: {diff.count:,}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


CHANGELOG_HEADER = (
    "# eduroam service location changelog\n"
    "\n"
    "Newest first. Each entry lists the service locations added to, removed from "
    "or moved within a region since the previous run.\n"
)


def update_changelog(path: str, entry: str, max_entries: int) -> str:
    existing = ""
    try:
        with open(path, encoding="utf-8") as fh:
            existing = fh.read()
    except OSError:
        pass

    body = existing.split("\n## ", 1)
    previous_entries = ("## " + body[1]) if len(body) > 1 else ""
    entries = [e for e in re.split(r"(?m)^(?=## )", previous_entries) if e.strip()]
    if entry:
        entries.insert(0, entry.rstrip() + "\n")
    if max_entries > 0:
        entries = entries[:max_entries]
    return CHANGELOG_HEADER + "\n" + "\n".join(e.rstrip() + "\n" for e in entries)


# --------------------------------------------------------------------------
# publishing
# --------------------------------------------------------------------------

class PagesPublisher:
    """
    Publishes the generated files to a GitHub Pages repository.

    Everything a run changes goes into a single commit via the Git data API, so
    the repository history is one commit per day of real change rather than one
    commit per file.
    """

    def __init__(self, cfg: dict, token: str, state_path: str):
        self.cfg = cfg
        self.token = token
        self.state_path = state_path
        self.state = read_json(state_path, {}) or {}

        repo = str(cfg.get("repo") or "").strip().strip("/")
        if repo.count("/") != 1 or not all(repo.split("/")):
            raise RuntimeError(f"publish.repo must look like 'owner/repo', got {repo!r}")
        self.owner, self.repo = repo.split("/")
        self.branch = str(cfg.get("branch") or "gh-pages").strip() or "gh-pages"
        self.subpath = str(cfg.get("path") or "").strip("/")
        self.site_url = str(cfg.get("site_url") or "").strip() or self.state.get("site_url", "")

    # -- low level -------------------------------------------------------
    def _api(
        self,
        method: str,
        path: str,
        payload: Optional[dict] = None,
        allow: Tuple[int, ...] = (),
    ) -> Tuple[int, dict]:
        data = json.dumps(payload).encode("utf-8") if payload is not None else None
        request = urllib.request.Request(
            f"{GITHUB_API}{path}",
            data=data,
            method=method,
            headers={
                "Authorization": f"Bearer {self.token}",
                "Accept": "application/vnd.github+json",
                "X-GitHub-Api-Version": "2022-11-28",
                "Content-Type": "application/json",
                "User-Agent": USER_AGENT,
            },
        )
        last: Optional[Exception] = None
        for attempt in range(3):
            try:
                with urllib.request.urlopen(request, timeout=self.cfg.get("http_timeout", 60)) as response:
                    body = response.read().decode("utf-8") or "{}"
                    return response.status, (json.loads(body) if body.strip() else {})
            except urllib.error.HTTPError as exc:
                detail = exc.read().decode("utf-8", "replace")[:400]
                if exc.code in allow:
                    return exc.code, {"message": detail}
                # Only transient classes are retried; 4xx will fail the same
                # way on a second attempt.
                if exc.code in (429, 500, 502, 503) and attempt < 2:
                    delay = 2 ** attempt * 3
                    LOG.warning("GitHub API %s (attempt %d), retrying in %ds", exc.code, attempt + 1, delay)
                    time.sleep(delay)
                    last = exc
                    continue
                raise RuntimeError(f"GitHub API {method} {path} failed: HTTP {exc.code} {detail}")
            except (urllib.error.URLError, OSError, ValueError) as exc:
                if attempt < 2:
                    time.sleep(2 ** attempt * 3)
                    last = exc
                    continue
                raise RuntimeError(f"GitHub API {method} {path} failed: {exc}")
        raise RuntimeError(f"GitHub API {method} {path} failed: {last}")

    def _save_state(self, **fields) -> None:
        self.state.update(fields)
        self.state["updated_at"] = iso(utcnow())
        write_atomic(self.state_path, json.dumps(self.state, indent=2, sort_keys=True).encode())

    def _repo_path(self, filename: str) -> str:
        return posixpath.join(self.subpath, filename) if self.subpath else filename

    # -- pages -----------------------------------------------------------
    def resolve_site(self) -> str:
        """Find (or turn on) the Pages site and work out its public URL."""
        if self.subpath not in ("", "docs"):
            LOG.warning(
                "GitHub Pages only serves from the repository root or /docs; "
                "publish.path=%r will be committed but not served",
                self.subpath,
            )

        status, info = self._api("GET", f"/repos/{self.owner}/{self.repo}/pages", allow=(403, 404))
        if status == 200 and info.get("html_url"):
            url = info["html_url"]
        elif status == 404 and self.cfg.get("enable_pages", True):
            LOG.info("GitHub Pages is not enabled on %s/%s -- turning it on", self.owner, self.repo)
            source = {"branch": self.branch, "path": f"/{self.subpath}" if self.subpath else "/"}
            status, info = self._api(
                "POST",
                f"/repos/{self.owner}/{self.repo}/pages",
                {"source": source},
                allow=(403, 404, 409, 422),
            )
            if status in (201, 204) and info.get("html_url"):
                url = info["html_url"]
            else:
                LOG.warning(
                    "Could not enable Pages automatically (%s). Enable it once by hand: "
                    "repository Settings -> Pages -> deploy from branch %r, folder %r.",
                    status,
                    self.branch,
                    f"/{self.subpath}" if self.subpath else "/",
                )
                url = self._guess_site_url()
        else:
            url = self._guess_site_url()

        self.site_url = url.rstrip("/") + "/"
        self._save_state(site_url=self.site_url)
        return self.site_url

    def _guess_site_url(self) -> str:
        owner = self.owner.lower()
        if self.repo.lower() in (f"{owner}.github.io", f"{owner}.github.com"):
            return f"https://{owner}.github.io/"
        return f"https://{owner}.github.io/{self.repo}/"

    # -- committing ------------------------------------------------------
    def _head(self) -> Tuple[Optional[str], Optional[str]]:
        status, ref = self._api(
            "GET",
            f"/repos/{self.owner}/{self.repo}/git/ref/heads/{self.branch}",
            allow=(404, 409),
        )
        if status != 200:
            LOG.info("Branch %r does not exist yet; creating it", self.branch)
            return None, None
        commit_sha = (ref.get("object") or {}).get("sha")
        if not commit_sha:
            return None, None
        _, commit = self._api("GET", f"/repos/{self.owner}/{self.repo}/git/commits/{commit_sha}")
        return commit_sha, (commit.get("tree") or {}).get("sha")

    def _existing_paths(self, tree_sha: str) -> set:
        status, tree = self._api(
            "GET",
            f"/repos/{self.owner}/{self.repo}/git/trees/{tree_sha}?recursive=1",
            allow=(404, 422),
        )
        if status != 200:
            return set()
        return {e.get("path") for e in tree.get("tree") or [] if e.get("type") == "blob"}

    def publish(self, updates: Dict[str, Optional[str]]) -> Optional[str]:
        """updates maps filename -> content, or filename -> None to delete."""
        if not updates:
            return None

        base_commit, base_tree = self._head()
        deletions = {n for n, c in updates.items() if c is None}
        present: set = set()
        if deletions and base_tree:
            present = self._existing_paths(base_tree)

        entries: List[dict] = []
        for name in sorted(updates):
            content = updates[name]
            repo_path = self._repo_path(name)
            if content is None:
                # Asking to delete something that was never committed is an error,
                # so only send deletions we can see in the current tree.
                if repo_path in present:
                    entries.append({"path": repo_path, "mode": "100644", "type": "blob", "sha": None})
                else:
                    LOG.debug("Skipping delete of %s (not in the published tree)", repo_path)
                continue
            _, blob = self._api(
                "POST",
                f"/repos/{self.owner}/{self.repo}/git/blobs",
                {
                    "content": base64.b64encode(content.encode("utf-8")).decode("ascii"),
                    "encoding": "base64",
                },
            )
            entries.append({"path": repo_path, "mode": "100644", "type": "blob", "sha": blob["sha"]})

        if not entries:
            return None

        LOG.info("Committing %d change(s) to %s/%s@%s", len(entries), self.owner, self.repo, self.branch)
        payload: Dict[str, object] = {"tree": entries}
        if base_tree:
            payload["base_tree"] = base_tree
        _, tree = self._api("POST", f"/repos/{self.owner}/{self.repo}/git/trees", payload)

        author = {
            "name": self.cfg.get("author_name") or "github-actions[bot]",
            "email": self.cfg.get("author_email") or "41898282+github-actions[bot]@users.noreply.github.com",
            "date": iso(utcnow()),
        }
        _, commit = self._api(
            "POST",
            f"/repos/{self.owner}/{self.repo}/git/commits",
            {
                "message": self.cfg.get("commit_message") or "Update eduroam service location maps",
                "tree": tree["sha"],
                "parents": [base_commit] if base_commit else [],
                "author": author,
                "committer": author,
            },
        )
        commit_sha = commit["sha"]

        if base_commit:
            self._api(
                "PATCH",
                f"/repos/{self.owner}/{self.repo}/git/refs/heads/{self.branch}",
                {"sha": commit_sha, "force": False},
            )
        else:
            self._api(
                "POST",
                f"/repos/{self.owner}/{self.repo}/git/refs",
                {"ref": f"refs/heads/{self.branch}", "sha": commit_sha},
            )

        self._save_state(last_commit=commit_sha, bootstrapped=True)
        return commit_sha


def resolve_token(publish_cfg: dict) -> str:
    token = os.environ.get(publish_cfg.get("token_env") or "GITHUB_TOKEN", "").strip()
    if token:
        return token
    path = publish_cfg.get("token_file") or ""
    if path:
        path = os.path.expanduser(path)
        try:
            with open(path, encoding="utf-8") as fh:
                return fh.read().strip()
        except OSError as exc:
            LOG.error("Cannot read token file %s: %s", path, exc)
    return ""


# --------------------------------------------------------------------------
# main
# --------------------------------------------------------------------------

def load_config() -> dict:
    """
    Merge config.json over the defaults.

    A missing file is fine -- the defaults are usable. A malformed one is not:
    silently falling back would run the job with the wrong publish target and
    the wrong attribution, which is worse than not running at all.
    """
    if not os.path.exists(CONFIG_PATH):
        LOG.info("No config at %s; using defaults", CONFIG_PATH)
        return dict(DEFAULT_CONFIG)
    try:
        with open(CONFIG_PATH, encoding="utf-8") as fh:
            user = json.load(fh)
    except ValueError as exc:
        raise SystemExit(f"{CONFIG_PATH} is not valid JSON: {exc}")
    except OSError as exc:
        raise SystemExit(f"Cannot read {CONFIG_PATH}: {exc}")
    if not isinstance(user, dict):
        raise SystemExit(f"{CONFIG_PATH} must contain a JSON object.")
    return deep_merge(DEFAULT_CONFIG, user)


def clip_to_regions(
    regions: Sequence[Region], placemarks: Sequence[Placemark]
) -> Tuple[Dict[str, List[Placemark]], int, int]:
    """Assign placemarks to regions. Returns (per region, assigned, unassigned)."""
    per_region: Dict[str, List[Placemark]] = {}
    matched: set = set()
    for region in regions:
        hits = [p for p in placemarks if region.boundary.contains(p.lon, p.lat)]
        per_region[region.code] = hits
        matched.update(p.key for p in hits)
        LOG.debug("%-6s %-28s %5d", region.code, region.name, len(hits))

    # Regions may overlap, so count distinct locations rather than summing the
    # per-region totals.
    assigned = len(matched)
    unassigned = len(placemarks) - assigned
    if unassigned:
        LOG.info(
            "%d location(s) fall outside every configured region "
            "(overseas entries, or a territory with no boundary file)",
            unassigned,
        )
    return per_region, assigned, unassigned


def enforce_guards(
    cfg: dict, total_upstream: int, assigned: int, previous_regions: dict, force: bool
) -> None:
    """Refuse to go any further if the upstream map looks broken."""
    if force:
        return
    if total_upstream < int(cfg["min_placemarks"]):
        raise SystemExit(
            f"Upstream map only has {total_upstream} locations, below the "
            f"min_placemarks guard of {cfg['min_placemarks']} -- refusing to publish. "
            "Re-run with --force to do it anyway."
        )
    known_before = sum(int(r.get("count", 0)) for r in previous_regions.values())
    if not known_before:
        return
    ratio = (known_before - assigned) / known_before
    if ratio > float(cfg["max_delete_ratio"]):
        raise SystemExit(
            f"Location count fell from {known_before} to {assigned} "
            f"({ratio:.0%} lost), above the max_delete_ratio guard of "
            f"{float(cfg['max_delete_ratio']):.0%} -- refusing to publish. "
            "Re-run with --force to do it anyway."
        )


def build_region_maps(
    cfg: dict,
    regions: Sequence[Region],
    per_region: Dict[str, List[Placemark]],
    previous_regions: Dict[str, dict],
    force: bool,
    dry_run: bool,
) -> Tuple[List[RegionDiff], Dict[str, dict], Dict[str, Optional[str]], List[str]]:
    """
    Diff each region against the inventory and rebuild the ones that moved.

    Returns (diffs, next inventory, files to publish, codes rebuilt).
    """
    regenerate_on_any = str(cfg.get("regenerate_on", "locations")).lower() == "any"
    icon = cfg.get("placemark_icon_url", "")
    attribution = attribution_for_kml(cfg)
    attribution_sha = attribution_digest(cfg)

    diffs: List[RegionDiff] = []
    inventory: Dict[str, dict] = {}
    changed: Dict[str, Optional[str]] = {}
    rebuilt: List[str] = []

    for region in regions:
        hits = per_region[region.code]
        previous = previous_regions.get(region.code) or {}
        diff = RegionDiff(region, previous, hits)
        diffs.append(diff)

        output_path = os.path.join(OUTPUT_DIR, region.filename)
        first_time = not previous
        missing_output = not os.path.exists(output_path)
        boundary_changed = previous.get("boundary_sha256") != region.digest
        name_changed = previous.get("name") != region.name
        attribution_changed = not first_time and previous.get("attribution_sha256") != attribution_sha

        if (
            force
            or first_time
            or missing_output
            or boundary_changed
            or name_changed
            or attribution_changed
            or diff.locations_changed
            or (regenerate_on_any and diff.anything_changed)
        ):
            kml = build_kml(region, hits, icon, attribution)
            if not dry_run:
                write_text_if_changed(output_path, kml)
            rebuilt.append(region.code)
            # Queued even when the local file was already byte-identical, so
            # that an interrupted publish is retried: the inventory and the
            # output only ever advance together.
            changed[region.filename] = kml
            LOG.info(
                "%s %s (%s, %d locations)",
                "[dry-run] would rebuild" if dry_run else "Rebuilt",
                region.filename,
                "forced" if force
                else "new region" if first_time
                else "new output" if missing_output
                else "boundary changed" if boundary_changed
                else "region renamed" if name_changed
                else "attribution changed" if attribution_changed
                else "locations changed",
                len(hits),
            )
        elif diff.metadata_changed:
            LOG.info(
                "%s: %d metadata-only change(s) upstream, not republished "
                "(regenerate_on=locations)",
                region.code,
                diff.metadata_changed,
            )
            inventory[region.code] = previous

        if region.code in inventory:
            continue
        # The inventory describes what is published, not what is upstream. A
        # region that was not rebuilt still has its old description text in the
        # published KML, so carry its entry forward untouched; otherwise
        # metadata churn alone would rewrite the inventory every run.
        inventory[region.code] = {
            "name": region.name,
            "count": len(hits),
            "boundary_sha256": region.digest,
            "attribution_sha256": attribution_sha,
            "placemarks": [p.inventory_record() for p in hits],
        }

    return diffs, inventory, changed, rebuilt


def retire_regions(
    regions: Sequence[Region],
    previous_regions: Dict[str, dict],
    changed: Dict[str, Optional[str]],
    dry_run: bool,
) -> None:
    """Withdraw maps whose region file has been deleted."""
    live = {r.code for r in regions}
    for code in sorted(set(previous_regions) - live):
        filename = f"eduroam_{code}.kml"
        LOG.warning("Region %r no longer configured -- retiring %s", code, filename)
        changed[filename] = None
        path = os.path.join(OUTPUT_DIR, filename)
        if os.path.exists(path) and not dry_run:
            os.remove(path)


def setup_logging(verbose: bool) -> None:
    os.makedirs(STATE_DIR, exist_ok=True)
    LOG.setLevel(logging.DEBUG)

    file_handler = logging.FileHandler(os.path.join(STATE_DIR, "run.log"), encoding="utf-8")
    file_handler.setFormatter(logging.Formatter("%(asctime)s %(levelname)-7s %(message)s"))
    file_handler.setLevel(logging.DEBUG)
    LOG.addHandler(file_handler)

    # A minimal cron environment can give us an ASCII console. Region names and
    # attribution text are user data, so degrade unrepresentable characters
    # rather than letting the job die on its own log output.
    for handle in (sys.stdout, sys.stderr):
        try:
            handle.reconfigure(errors="backslashreplace")
        except (AttributeError, ValueError, OSError):
            pass

    stream = logging.StreamHandler(sys.stderr)
    stream.setFormatter(logging.Formatter("%(levelname)-7s %(message)s"))
    stream.setLevel(logging.DEBUG if verbose else logging.WARNING)
    LOG.addHandler(stream)


def acquire_lock() -> "object":
    os.makedirs(STATE_DIR, exist_ok=True)
    handle = open(os.path.join(STATE_DIR, "run.lock"), "w")
    try:
        fcntl.flock(handle, fcntl.LOCK_EX | fcntl.LOCK_NB)
    except OSError:
        raise SystemExit("Another run is already in progress; exiting.")
    handle.write(f"{os.getpid()}\n")
    handle.flush()
    return handle


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.strip().splitlines()[1])
    parser.add_argument("-v", "--verbose", action="store_true", help="log progress to stderr")
    parser.add_argument("-f", "--force", action="store_true", help="re-download and rebuild everything")
    parser.add_argument("-n", "--dry-run", action="store_true", help="compute changes but write and publish nothing")
    args = parser.parse_args(argv)

    verbose = args.verbose or truthy_env("EDUROAM_VERBOSE")
    force = args.force or truthy_env("EDUROAM_FORCE")

    setup_logging(verbose)
    lock = acquire_lock()
    started = utcnow()
    LOG.info("=== run started %s (version %s) ===", iso(started), __version__)

    cfg = load_config()
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    # ---- regions and source data -------------------------------------
    regions = load_regions(REGIONS_DIR)
    LOG.info("Loaded %d region(s): %s", len(regions), ", ".join(r.code for r in regions))

    source_bytes, source_meta = fetch_source(cfg, force)
    placemarks = parse_source_kml(source_bytes)
    LOG.info("Upstream map holds %d unique service location(s)", len(placemarks))

    inventory_path = os.path.join(STATE_DIR, "inventory.json")
    inventory = read_json(inventory_path, {}) or {}
    previous_regions: Dict[str, dict] = inventory.get("regions", {}) or {}

    per_region, assigned, unassigned = clip_to_regions(regions, placemarks)
    enforce_guards(cfg, len(placemarks), assigned, previous_regions, force)

    diffs, new_inventory_regions, changed_files, rebuilt = build_region_maps(
        cfg, regions, per_region, previous_regions, force, args.dry_run
    )
    retire_regions(regions, previous_regions, changed_files, args.dry_run)

    # ---- reports ------------------------------------------------------
    stamp_day = started.strftime("%Y-%m-%d")
    # Time included so that several runs on the same day stay distinguishable.
    entry = render_change_entry(started.strftime("%Y-%m-%d %H:%M UTC"), diffs)
    last_changed = stamp_day if entry else (inventory.get("last_changed") or "")

    publish_cfg = cfg["publish"]
    publish_state_path = os.path.join(STATE_DIR, "publish.json")
    publisher: Optional[PagesPublisher] = None
    publish_state = read_json(publish_state_path, {}) or {}
    site_url = str(publish_cfg.get("site_url") or "").strip() or publish_state.get("site_url", "")

    if publish_cfg.get("enabled") and not args.dry_run:
        token = resolve_token(publish_cfg)
        if not str(publish_cfg.get("repo") or "").strip():
            LOG.error("Publishing is enabled but publish.repo is not set. Skipping publish.")
        elif not token:
            LOG.error(
                "Publishing is enabled but no token was found (env %s). Skipping publish.",
                publish_cfg.get("token_env"),
            )
        else:
            try:
                publisher = PagesPublisher(publish_cfg, token, publish_state_path)
                if site_url:
                    # Already known from config or a previous run; a no-op run
                    # then costs zero GitHub API calls.
                    publisher.site_url = site_url
                else:
                    site_url = publisher.resolve_site()
            except RuntimeError as exc:
                LOG.error("Could not reach the Pages repository: %s", exc)
                publisher = None

    rows = [
        (region, len(per_region[region.code]),
         int(previous_regions[region.code]["count"]) if region.code in previous_regions else None)
        for region in regions
    ]
    leaderboard = render_leaderboard(rows, cfg, last_changed, iso(started), site_url, assigned)
    index_html = render_index_html(rows, cfg, last_changed, site_url, assigned)
    changelog = update_changelog(
        os.path.join(OUTPUT_DIR, CHANGELOG_NAME), entry, int(cfg["changelog_max_entries"])
    )

    if not args.dry_run:
        for name, content in (
            (LEADERBOARD_NAME, leaderboard),
            (INDEX_NAME, index_html),
            (CHANGELOG_NAME, changelog),
        ):
            if write_text_if_changed(os.path.join(OUTPUT_DIR, name), content):
                changed_files[name] = content
        # Stops GitHub Pages running the files through Jekyll.
        nojekyll = os.path.join(OUTPUT_DIR, NOJEKYLL_NAME)
        if not os.path.exists(nojekyll):
            write_atomic(nojekyll, b"")
            changed_files[NOJEKYLL_NAME] = ""
        elif not publish_state.get("bootstrapped"):
            changed_files[NOJEKYLL_NAME] = ""

    tracked = [d for d in diffs if not d.first_run]
    totals = {
        "added": sum(len(d.added) for d in tracked),
        "removed": sum(len(d.removed) for d in tracked),
        "moved": sum(len(d.moved) for d in tracked),
        "metadata_changed": sum(d.metadata_changed for d in diffs),
        "baselined_regions": sum(1 for d in diffs if d.first_run and d.count),
    }

    if entry and not args.dry_run:
        record = {
            "run": iso(started),
            "source_sha256": source_meta.get("sha256", ""),
            "totals": dict(totals, regions=len(regions), locations=assigned, unassigned=unassigned),
            "regions": {
                d.region.code: d.summary() for d in diffs if d.locations_changed
            },
        }
        jsonl_path = os.path.join(OUTPUT_DIR, CHANGES_JSONL)
        lines = []
        try:
            with open(jsonl_path, encoding="utf-8") as fh:
                lines = [ln for ln in fh.read().splitlines() if ln.strip()]
        except OSError:
            pass
        lines.append(json.dumps(record, sort_keys=True))
        cap = int(cfg["changes_max_entries"])
        if cap > 0:
            lines = lines[-cap:]
        body = "\n".join(lines) + "\n"
        write_atomic(jsonl_path, body.encode("utf-8"))
        changed_files[CHANGES_JSONL] = body

    # ---- publish ------------------------------------------------------
    published = 0
    if publisher and changed_files:
        try:
            commit = publisher.publish(changed_files)
            published = len(changed_files)
            site_url = publisher.site_url
            if commit:
                LOG.info("Committed %d file(s) as %s", published, commit[:10])
            LOG.info("Published at %s", site_url)
        except RuntimeError as exc:
            LOG.error("Publishing failed: %s", exc)
            LOG.error("Local files are up to date; the next run will retry the push.")
            published = -1
    elif publisher:
        LOG.info("Nothing changed -- repository left untouched")

    # ---- persist state -------------------------------------------------
    if not args.dry_run and published >= 0:
        # Data only. Anything that changes from run to run regardless of the
        # data belongs in last_run.json, so that a quiet day produces a
        # byte-identical inventory and therefore no commit.
        write_atomic(
            inventory_path,
            json.dumps(
                {
                    "version": __version__,
                    "last_changed": last_changed,
                    "regions": new_inventory_regions,
                },
                indent=1,
                sort_keys=True,
            ).encode(),
        )
        write_atomic(
            os.path.join(STATE_DIR, "last_run.json"),
            json.dumps(
                {
                    "generated": iso(started),
                    "source_sha256": source_meta.get("sha256", ""),
                    "locations": assigned,
                    "unassigned": unassigned,
                    "regions": len(regions),
                    "rebuilt": sorted(rebuilt),
                },
                indent=2,
                sort_keys=True,
            ).encode(),
        )

    # ---- summary --------------------------------------------------------
    summary = (
        f"{assigned:,} locations in {len(regions)} regions; "
        f"+{totals['added']} -{totals['removed']} ~{totals['moved']}"
    )
    if totals["baselined_regions"]:
        summary += f"; {totals['baselined_regions']} region(s) baselined"
    summary += f"; {len(rebuilt)} map(s) rebuilt"
    LOG.info("=== run finished: %s ===", summary)

    if args.dry_run:
        print(f"[dry-run] {summary}")
    elif entry or rebuilt or changed_files:
        print(f"eduroam maps updated: {summary}")
        if publisher and published > 0:
            print(f"Published {published} file(s) to {site_url}")
    elif verbose:
        print(f"No changes. {summary}")

    lock.close()
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except SystemExit:
        raise
    except KeyboardInterrupt:
        sys.exit(130)
    except Exception as exc:  # noqa: BLE001 - cron wants a readable failure
        LOG.exception("Unhandled error: %s", exc)
        print(f"eduroam_maps.py failed: {exc}", file=sys.stderr)
        sys.exit(1)
